"""empty message

Revision ID: 1f163f172003
Revises: 
Create Date: 2022-07-11 15:55:13.525778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f163f172003'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_type',
    sa.Column('user_type_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_type_id', name='user_type_pkey'),
    sa.UniqueConstraint('type', name='user_type_type_key')
    )
    # ### end Alembic commands ###
