"""empty message

Revision ID: 40e3241dd1f2
Revises: d8f1056899f9
Create Date: 2022-07-12 13:40:23.361166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40e3241dd1f2'
down_revision = 'd8f1056899f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category')
    )
    op.create_table('news',
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('news_heading', sa.String(), nullable=False),
    sa.Column('news_info', sa.String(), nullable=False),
    sa.Column('news_date', sa.DateTime(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=True),
    sa.Column('news_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['news_category_id'], ['news_category.category_id'], ),
    sa.PrimaryKeyConstraint('news_id')
    )
    op.create_table('journalist_news_mapping',
    sa.Column('journalist_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['journalist_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['news_id'], ['news.news_id'], ),
    sa.PrimaryKeyConstraint('journalist_id', 'news_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journalist_news_mapping')
    op.drop_table('news')
    op.drop_table('news_category')
    # ### end Alembic commands ###
