"""empty message

Revision ID: 82d9b38ee2e4
Revises: 77e723c71a9d
Create Date: 2022-07-20 10:49:41.891484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82d9b38ee2e4'
down_revision = '77e723c71a9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'image')
    # ### end Alembic commands ###
