"""empty message

Revision ID: d8f1056899f9
Revises: 80af19486a4b
Create Date: 2022-07-12 13:39:22.610878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8f1056899f9'
down_revision = '80af19486a4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temporary_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temporary_table',
    sa.Column('temp_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('temp_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('temp_id', name='temporary_table_pkey')
    )
    # ### end Alembic commands ###
